### ISSUE TITLE
swoole 增加断点调试代码的功能，降低调试难度，还有就是代码热更新提供更好的工具

### ISSUE THREAD

**Issue by munggruel** [swoole/community-chinese#64]
swoole 增加断点调试代码的功能，降低调试难度，还有就是代码热更新提供更好的工具

**Comment by munggruel** [comment]
不然swoole 上面调试bug的难度币 php-fpm下高了太多， 还有就是 查内存泄漏的 工具能开源么？这个算是比较重要的工具了

**Comment by Moln** [comment]
热更新可以通过自行用php开发解决。
参考 Laminas (Zend Framework) 实现：
 https://github.com/mezzio/mezzio-swoole/tree/master/src/HotCodeReload

至于断点调试： https://github.com/swoole/sdebug
我还没用上 sdebug，不知道怎么样。

**Comment by munggruel** [comment]
sdebug 在 cgwin下能编译么？

**Comment by sy-records** [comment]
可以用yasd https://github.com/swoole/yasd
